apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}{{- with .Values.database.suffix }}-{{ . }}{{- end }}-rw
  namespace: dbaas-{{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    cnpg.io/cluster: {{ .Release.Name }}{{- with .Values.database.suffix }}-{{ . }}{{- end }}
    role: primary 